server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cashflow
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}'
          max_wait_time: 3s
    static_configs:
      - targets:
          - localhost
        labels:
          job: cashflow
          __path__: /var/log/*.log